spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_db
    username: root
    password: arvind9600
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
